name: main code

on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - *

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests.py
